export const stationeryList = [
  {
    id: "stationeryList",
    name: "Bút chì bằng gỗ khổng lồ độc đáo sáng tạo RYVN",
    price: "13.500",
    img: "https://cf.shopee.vn/file/01e6d3f1b1692e9336937e5e9ff5ad26",
    time: "10 giờ trước",
    address: "Tp Hồ Chí Minh",
    description: "Bút chì siêu to khổng lồ cần bán",
  },
  {
    id: "stationeryList2",
    name: "Bút vẽ Marker Color 48 màu tặng kèm túi bút dạ viết - vẽ 2 đầu chuyên nghiệp",
    price: "55.000",
    img: "https://vn-test-11.slatic.net/p/0806868910db9bcebe98a24ed740f8ef.jpg",
    time: "5 giờ trước",
    address: "Tp Hồ Chí Minh",
    description: "Bút vẽ Marker, càng vẽ càng ghê",
  },
  {
    id: "stationeryList3",
    name: "Màu Nước Solid Water Color Cao Cấp 12/18/24/36M Tặng 2 Bút Nước, 2 Mút -Lalunavn - B30",
    price: "44.990",
    img: "https://prices.vn/storage/photo/product/bo-mau-nuoc-water-color-cao-cap-12-1645547387095.png",
    time: "30 phút trước",
    address: "Tp Hồ Chí Minh",
    description: "Màu nước Solid Water, dùng là phê",
  },
  {
    id: "stationeryList4",
    name: "Sổ còng Binder A4 B5 A5 8 còng kèm ruột giấy refill làm planner bullet journal SEREIN",
    price: "17.900",
    img: "https://cf.shopee.vn/file/11f901c92284a837f82acac086b9ea5e",
    time: "3 giờ trước",
    address: "Tp Hồ Chí Minh",
    description: "Sổ còng Binder, dùng là mê",
  },
];

export const techDevice = [
  {
    id: "techDevice1",
    name: "Iphone 14 Pro Max",
    price: "20.000.000",
    img: "https://cdn.tgdd.vn/Products/Images/42/251192/iphone-14-pro-max-den-thumb-600x600.jpg",
    time: "1 giờ trước",
    address: "Tp Hồ Chí Minh",
    brand: "Apple",
    color: "Purple",
    memory: "512gb",
    status: "99%",
    guarantee: "1 year",
    description: "iphone 14 màu tím cực mộng mơ",
  },
  {
    id: "techDevice2",
    name: "Macbook Pro 2019",
    price: "30.000.000",
    img: "https://bizweb.dktcdn.net/100/046/882/products/macbook-pro-13-inch-touch2019-core-i7-8569u-2-8-ghz-ram-8gb-16gb-ssd-256gb-512gb-1tb-mv982-model-a1989-emc-3358.jpg?v=1658205236260",
    time: "5 giờ trước",
    address: "Tp Hồ Chí Minh",
    brand: "Apple",
    chip: "Core i5",
    ram: "8GB",
    hard_drive: "256GB SSD",
    graphic_card: "Graphics 645",
    screen_size: "13.3 inch",
    status: "90%",
    guarantee: "6 month",
    description: "Macbook còn mới keng",
  },
  {
    id: "techDevice3",
    name: "Máy ảnh Canon",
    price: "10.000.000",
    img: "https://img.websosanh.vn/v2/users/review/images/u13i0dtj9hsqs.jpg?compress=85",
    time: "30 phút trước",
    address: "Tp Hồ Chí Minh",
    brand: "Canon",
    status: "90%",
    guarantee: "1 year",
    description: "Máy ảnh Canon chụp ảnh rất nét",
  },
  {
    id: "techDevice4",
    name: "Samsung Galaxy S23",
    price: "15.000.000",
    img: "https://www.stuff.tv/wp-content/uploads/sites/2/2023/02/Samsung-Galaxy-S23-review-in-hand-front.jpg?w=1080",
    time: "1 giờ trước",
    address: "Tp Hồ Chí Minh",
    brand: "Samsung",
    color: "Black",
    memory: "256gb",
    status: "90%",
    guarantee: "1 year",
    description: "Điện thoại Samsung siêu đỉnh đây mại dô mại dô",
  },
];

export const bookList = [
  {
    id: "bookList1",
    name: "Giáo trình chủ nghĩa xã hội khoa học",
    status: "99%",
    price: "30.000",
    img: "https://nxbctqg.org.vn/img_data/images/526072223378_cnkv.jpg",
    time: "1 giờ trước",
    address: "Tp Hồ Chí Minh",
    description: "Mua sách này đọc sẽ trở nên thông thái",
  },
  {
    id: "bookList2",
    name: "Giáo trình chủ nghĩa Mac-Lenin",
    status: "95%",
    price: "50.000",
    img: "https://cdn.luatminhkhue.vn/lmk/article/Sach-luat/Giao-trinh-Triet-hoc-Mac-Lenin.jpg",
    time: "5 giờ trước",
    address: "Tp Hồ Chí Minh",
    description:
      "Vật chất quyết định ý thức và ý thức tác động trở lại vật chất",
  },
  {
    id: "bookList3",
    name: "Giáo trình tư tưởng Hồ Chí Minh",
    status: "94%",
    price: "40.000",
    img: "https://www.nxbctqg.org.vn/img_data/images/238626889476_ttkc.jpg",
    time: "2 giờ trước",
    address: "Tp Hồ Chí Minh",
    description: "Sự vĩ đại của Bác Hồ",
  },
  {
    id: "bookList4",
    name: "Giáo trình Kinh tế chính trị Mac-Lenin",
    status: "99%",
    price: "35.000",
    img: "https://stbook.vn/static/covers/CP111BK120211115135135/cover.clsbi",
    time: "10 giờ trước",
    address: "Tp Hồ Chí Minh",
    description:
      "bạn biết giá trị thặng dư là gì ko, mua và đọc sách này sẽ rõ",
  },
];

export const uniformList = [
  {
    id: "uniformList1",
    name: "Đồng phục vovinam FPT",
    size: "L",
    color: "blue",
    price: "50.000",
    img: "https://sieuthivothuat.com/upload/product/217417364011.jpg",
    time: "5 giờ trước",
    address: "Tp Hồ Chí Minh",
    description: "Mình cần pass lại bộ đồng phục vovinam FPT này ạ",
  },
  {
    id: "uniformList2",
    name: "Đồng phục Hutech",
    size: "M",
    color: "orange",
    price: "100.000",
    img: "https://uvi.vn/wp-content/uploads/2021/11/Chup-anh-mac-dong-phuc-ao-thun-Hutech.jpeg",
    time: "10 giờ trước",
    address: "Tp Hồ Chí Minh",
    description: "Mình cần pass lại bộ đồng phục Hutech này ạ",
  },
];
